name: "Terraform Plan & Apply"

on: push

jobs:
  test-infrastructure:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Terraform
        uses: julanu/composite-actions/terraform-cli-deploy@dev-release
        with:
          initArguments: "-reconfigure"
          additionalArguments: "-var-file=env/randoms.tfvars -no-color"
          working-directory: "infra/"
