name: "Terraform Plan & Apply"

on:
  workflow_dispatch:

jobs:
  test-infrastructure:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Terraform
        uses: julanu/composite-actions/terraform-cli-deploy@dev-release
        with:
          initArguments: "-reconfigure"
          additionalArguments: "-var-file=vars/randoms.tfvars -no-color"
          workingDirectory: "infra/"
